[6.9.z] Vault integration to access secrets via DynaConf
SatelliteQE/testfm pull request #292
Opened 2022-05-24 14:51 UTC by Gauravtalreja1

Cherrypick of #290 
Signed-off-by: Gaurav Talreja <gtalreja@redhat.com>

2022-05-24 15:13 UTC, jyejare requested changes
I think you should keep vault integration aside from pre-commit changes.

2022-05-24 16:34 UTC, Gauravtalreja1 commented on .flake8
> +max-line-length = 100
we moved to 100 for 6.10.z and master branches already as similar to robottelo, 
And pre-commit changes are long overdue for the 6.9.z and 6.10z branches. Older hooks broke GHA checks for black on these branches, which forced us to update those hooks

2022-05-24 16:54 UTC, Gauravtalreja1 commented on .flake8
> +max-line-length = 100
@jyejare GHA was failing to resolve the latest dynaconf dependency due to old python version 3.6, so included one more cherrypick to run GHA on Py3.8 and Py3.9, which fixes failing GHA, request to re-review.

2022-05-25 07:44 UTC, jameerpathan111 approved these changes

2022-05-25 07:45 UTC, merged